### ISSUE TITLE
Context URI in spec is 404

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#1054]
Under the Context section (https://identity.foundation/sidetree/spec/#context)

We have a context URI that returns 404:
https://identity.foundation/sidetree/context-v1.jsonld

**Comment by OR13** [comment]
https://github.com/decentralized-identity/sidetree/pull/1055/files

This would create the file

but the spec would still need to be updated to not error...

I think I have sucessfully beaten all the broken JSON-LD out of sidetree, so that it will work with VCs without extension... so this file should probably not be needed... unless we want to expose specific sidetree relateted services or verificaiton methods in the did document...

or if they fail to include canonicalId or equivalentId in did core.

**Comment by troyronda** [comment]
Fixed in latest spec.
