### ISSUE TITLE
Create sidetree-specific DID Document constraints

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#110]
Because storage size could potentially limit the ability for folks to run full nodes at scale, we need to create a more strict set of sidetree-specific DID Document constraints that limit the size and use of props/values. Here are a few possible constraints we may want to enforce:

1. Limit size/content of DID Fragment Identifiers
2. Limit key size/content to a whitelist of recognized schemes
3. Fail an op/batch for inclusion of non-standard props

**Comment by OR13** [comment]
i've been meaning to write some JSON Schema for basic operation validation.

I think we should start with a whitelist for patches, including supported key schemes, and size definitions.

I think the batch should fail, to punish any nodes and people who rely on them for not validating user input... I think this might be a problem though since you might need to resolve before validation is possible if you don't know size constraints for patches... or we have to be stricter in terms of what is a valid patch (replace only, etc..).

I think the whitelist can be expanded as other patch needs become known.

Since a sidetree DID Doc is really just a series of create and updates, this is really a request for patch and create validation.

Seems like this update ticket might be better place for patch validation discussion: https://github.com/decentralized-identity/sidetree/issues/262

**Comment by thehenrytsai** [comment]
I think most of the requirements mentioned above are met:

1. DID fragment must be a supported multihash.
1. We white list op-active key type and format and key length.
1. We discard/penalize batch that fail ANY op validation.

So I am going to close this, let's file specific issues with label `bug` when we found any, I'm sure there are some.
