### ISSUE TITLE
Unable to create -and- update a DID until anchoring of each operation?

### ISSUE THREAD

**Issue by stskeeps** [decentralized-identity/sidetree#1124]
Getting this when trying to do creation and update within short time: 'An operation request already exists in queue for DID' .. 'only one is allowed at a time'

The spec seems to specify this restraint for a creation/recover/deactive, but can it really be true we have to wait for an anchoring to make an update of a DID?

**Comment by csuwildcat** [comment]
@stskeeps currently the protocol assumes you anchor a Create before subsequent other types of operations, but they shouldn't have to be in order - this may just be our node enforcing that someone not fire multiple ops at it from the same ID. I can see the value in going from unachored to Update right away, so let check on the details.

**Comment by thehenrytsai** [comment]
@stskeeps, it's not so much that you have to wait for a DID to be anchored before sending out an update, @csuwildcat is right that the order should not matter. It is however a protocol requirement that a batch must not contain more than 1 operation per DID, this is more of an anti-spam mechanism against a particular DID.

**Comment by stskeeps** [comment]
Playing this a bit from UI side: an anchoring (on Bitcoin, with ION) would be 10 minutes-ish(?). It's fairly normal to see a user 'create an account' (should be 'active' at that point) and then adjusting security settings, such as adding additional recovery methods => a update to a DID. This kinda leads to bad UX in my opinion.

While ION's not sidetree directly, there's already the idea there that 'If you want to write transactions containing more than 100 operations, you are required to lock some BTC for exactly 4500 blocks using a time locked transaction.' [1] -- as a kind of guard against strong spamming of the network. 

In such a case, isn't it then better to make it up to the node to ask for Proof of Work from a submitter or other methods before letting updates into a batch? -- which would then be adding to processing load on other nodes

[1] https://github.com/decentralized-identity/ion/blob/master/docs/design.md

**Comment by thehenrytsai** [comment]
Proof-of-fee is aimed at preventing spam against the network in general as you pointed out, but does not prevent spam against a particular DID. Specifically, without this requirement, if I really don't like a particular DID, I could lock some BTC, and start generating 10000 updates against a particular DID in the same batch every 10 minutes, not saying this in itself is a major problem because sidetree spec does have a commit-reveal scheme that weeds out the fake ops quickly, but nonetheless in v1 we took an aggressive stance at preventing this from happening in the first place. In terms of additional processing load, I'd think it is so small (walking an array once), it is negligible. This is not to say that we couldn't lift this restriction in a subsequent update to the spec, if the community feels strongly about this.

Your point on UI is valid, async nature of the ops is a limitation to UI design. But anchoring (on Bitcoin especially) is inherently asynchronous, so even if the update goes in with create op in the same batch, it would still take ~10 minute, so problem is not entirely gone. I'd say the UI designer may need to design a flow that best accommodate this async nature, perhaps during initialization, don't send the create op until the initial "state" is truly determined, but then again I am not a UI designer!

**Comment by nikolockenvitz** [comment]
I have a question about this spam protection: Doesn't it open up a DoS attack vector if only one update operation per DID suffix per anchoring batch is allowed by an ION node? One could create an invalid operation and the actual owner of the DID would be blocked because there is already a pending operation that needs to be anchored first.
I think the only way of correct spam protection would be checking reveal value and signature of the operation.
In my understanding this is not done currently by an ION node, right?

**Comment by thehenrytsai** [comment]
Hi @nikolockenvitz, one could certainly create an invalid operation pretending that it is for DID X, but it is not a valid attack because that attackers needs to magically know when and where an operation for DID X is coming through, and even so, the attacker can never stop the owner DID X from submitting their own transaction.

**Comment by nikolockenvitz** [comment]
Regarding the first aspect: Well yes, but an attacker could easily submit invalid operations in a regular interval or even, when observing the Sidetree node, directly after a batch was anchored. Additionally, you can easily see which nodes have been used by a DID X in the past - so you would need to configure a lot of Sidetree nodes as a DID owner to switch to another node. The problem is, when picking a single or just a few DIDs, it does not take much effort for an attacker to submit invalid operations for those every 10 minutes on a few nodes.

Yes, submitting the transaction by themselves will work, but relying on Sidetree nodes that employ authentication could also (partially) solve the problem.

**Comment by nikolockenvitz** [comment]
To clarify: This limitation of one update operation per batch (per DID suffix) is rooted in the implementation and not in the protocol, right? Because there I only find this for the Core Index File (i.e. Create, Recover, Deactivate) but not for the update operation.

**Comment by csuwildcat** [comment]
Niko, I think you might not fully understand the commit/reveal scheme, because spamming a DID by submitting invalid ops is exactly what it eliminates. The commitment is a secret no one but the DID owner knows, and because it's a hash check, even if an attacker submitted 1 million invalid txns, the hash checking would filter them out virtually instantly. The attacker doing this is a totally waste, as all Sidetree nodes would deduce this effortlessly. Also, your comments seem to suggest you may believe the system relies on users picking nodes and having some relationship with them. It's not a system where you're picking a node to act as your isolated registrar and need to do a special process to move between them, you can just anchor with any node at any time.

**Comment by csuwildcat** [comment]
> To clarify: This limitation of one update operation per batch (per DID suffix) is rooted in the implementation and not in the protocol, right? Because there I only find this for the Core Index File (i.e. Create, Recover, Deactivate) but not for the update operation.

No, it's rooted in the protocol: you can only have one operation of any type per batch/anchor, meaning spamming with invalid txns is essentially futile, because even if you spun up 100 nodes to do 100 Bitcoin txns every block in Bitcoin, it would still be so easy for all the other nodes to filter (due to the commit/reveal) that you'd have wasted a ton of money for nothing.

**Comment by nikolockenvitz** [comment]
> 
> 
> Niko, I think you might not fully understand the commit/reveal scheme, because spamming a DID by submitting invalid ops is exactly what it eliminates. The commitment is a secret no one but the DID owner knows, and because it's a hash check, even if an attacker submitted 1 million invalid txns, the hash checking would filter them out virtually instantly. The attacker doing this is a totally waste, as all Sidetree nodes would deduce this effortlessly. Also, your comments seem to suggest you may believe the system relies on users picking nodes and having some relationship with them. It's not a system where you're picking a node to act as your isolated registrar and need to do a special process to move between them, you can just anchor with any node at any time.

Makes sense. So if the Sidetree node checks the reveal value, there is no way for an attacker to do this kind of DoS. But what is this anti-spam mechanism then about?

**Comment by nikolockenvitz** [comment]
> 
> 
> > To clarify: This limitation of one update operation per batch (per DID suffix) is rooted in the implementation and not in the protocol, right? Because there I only find this for the Core Index File (i.e. Create, Recover, Deactivate) but not for the update operation.
> 
> No, it's rooted in the protocol: you can only have one operation of any type per batch/anchor, meaning spamming with invalid txns is essentially futile, because even if you spun up 100 nodes to do 100 Bitcoin txns every block in Bitcoin, it would still be so easy for all the other nodes to filter (due to the commit/reveal) that you'd have wasted a ton of money for nothing.

Ok. I only found that for the Create/Recover/Deactivate in the spec but not for the Update. What is the reason that you can only have one operation per batch per DID Suffix? If the underlying anchoring system is used to create a consistent, deterministic, global order of DID operations, what is the difference between having two operations in one batch compared to having them in two subsequent batches? Do you view them as unordered in the batch?

**Comment by nikolockenvitz** [comment]
Ah I see 👍. With spam you refer to spamming the network or the resolvers? Because all operations are still authorized by the DID owner, right?

**Comment by thehenrytsai** [comment]
Spam as in: "intentionally crafted junk data that are useless to running nodes". In the case of if we allow a batch of 10 000 ops for the same DID, then the nodes are forced to keep the data, and also it will start to impact resolution of that particular DID, since let's not forget, while hash check is cheap, the node still needs to grab all that data from the underlying DB.

**Comment by nikolockenvitz** [comment]
Makes sense, I think I understand that a bit better now. Thanks for your help @thehenrytsai @csuwildcat

**Comment by thehenrytsai** [comment]
Feel free to open new issues as they arise.
