### ISSUE TITLE
Add commit/reveal scheme to enable fast next-op proof of legitimacy and prevent DDoR (DID Denial of Resolution) spam attacks

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#252]
Presently, anyone can claim a batch might contain an operation for a given DID, thus a malicious actor could spam anchor file DID Suffix assertions against a target DID, which would amass an unusually large number of batch files to fetch and check at resolution time. Presently, we are mitigating this by only allowing one DID op per DID per batch file, to at least force the attacker to pay for multiple transactions. However, there may be a far better solution - here's how it would work:

1. Alice creates her first operation, and part of that op is a next-op commitment to the hash of a random value that is included in the signed portion of the op payload.
2. Alice is the only one who knows the commitment value, thus when she needs to do her next update op, she creates the op and includes a reveal of the hashed commitment value, which is paired with her DID Suffix claim in the Anchor file. (she also adds a new next-op commitment value to her update op, so she can repeat the process for the next op)
3. Anyone that has processed Alice's first op would know that the next value they are looking for is an Anchor file DID Suffix value that matches the commitment hash she included with her previous op, which only Alice knows and can reveal.

This basically halts the entire class of attack by providing a fast hash/value check nodes can perform against the accrued anchor file DID Suffix claims to chew through any spurious DID op inclusion claims very quickly, before ever incurring a batch download.

**Comment by csuwildcat** [comment]
Here's a visual walk-through of how this would work: 

![next-op-commitments](https://user-images.githubusercontent.com/131786/60448950-7be10b80-9bdb-11e9-827e-6c4af59cae50.png)

**Comment by OR13** [comment]
IMO, this is a critical protocol fix.

This would be an excellent candidate for protocol upgrade integration tests, where we change both the commit algorithm and the operation hash algorithm, and show stability.

**Comment by csuwildcat** [comment]
Additional note about regular next-op commitments vs recovery ops:

There should be a next-op commitment value created for each op at the time of update, and we can debate whether to encrypt that value in payload or not (I would prefer not, as it will eat DID Doc space), but there is one thing that we must enforce: recovery ops should have a different per-recovery next-op commitment value that is encrypted in the DID Doc, to ensure that it is maximally available and persisted.

**Comment by OR13** [comment]
The word encrypted is confusing me here... Isn't it the case that all operation data is plaintext, and a chain of scheme(secretN, nextOpHash) => nextOpCommit, is used to protect nodes from downloading bad data?

There is no encryption in a commitment scheme like this, outside of the responsibility of the operation creator for protecting their secret, just like they must currently protect their signing key.

A system creates 2 keypairs (primary and recovery) and 2 next_op_secret (primary and recovery).

The system then cold storages the recovery `private key` and` next_op_secret`.

The system then constructs the DID Create operation, includes the primary and recovery public keys, and commits to the primary and recovery secrets.

For each update, the system generates a new secret, and reveals an old one.

If recovery or primary `next_op_secret` is leaked, worst case is the attacker can cause DID Doc bloat, until a new correctly signed operation is published.

If primary signing key is leaked but `next_op_secret` is not, signing key should not be trusted, but no DID Document tamper operation is possible, and recovery key and recovery `next_op_secret` are required to disable the DID Doc bloat attack.

If recovery signing key is leaked, its GG.

**Comment by OR13** [comment]
Not sure if this is safe: https://github.com/decentralized-identity/element/blob/feat/commit-reveal-poc/packages/element-lib/src/func/commitRevealPOC.spec.js

The idea here is to avoid needing to store the secret, and instead compute the secret as a signature of public information, so that anyone who controls the signing key can perform an operation.

There are some assumptions here:

- we assume that base64url(sha256(secp256k1.sign( previousOperationHash OR previousTransactionTimeHash, privateKey )) generates enough entropy to be used in a commit reveal scheme.
- we assume that compromise of a signing key can only be mitigated with a recover operation.
- we assume that the minimum entropy needed for commit reveal would be used IRL.

For the create operation, both the primary and recovery commitments should be to the sha256 of signature of didUniqueSuffix, after create they should be to the previousOperationTransactionTimeHash.

Why have 2 commit reveal chains? why not 1?

Since the next commit is a function of the private key, the private key must be available for signing. 

Since the recovery key cannot be available for signing (because it should be cold storage / shattered secret), the commit reveal chain for recovery must extend only when recovery operations are performed.

See this picture:

![Untitled drawing](https://user-images.githubusercontent.com/8295856/60853262-e2a88b00-a1c0-11e9-8451-e61aecda6e91.png)

Note the first recover secret is the sha25 of secp256k1.sign of didUniqueSuffix, but the recover secret is the sha25 of secp256k1.sign of previousOperationTransactionTimeHash.

The recover operation should replace compromised keys, and should include a new primary commitment, so that non recovery keys can be used for subsequent updates.

While this approach avoids self encrypting secrets, it does force nodes to consider if the revealed value is a revealed primary or revealed recovery commitment, however, when looking at an anchorFile, this is simply 2 string compares for strings of length `size_of_revealed_secret`.

I think this scheme is safe, but it would be awesome to have someone more familiar point us to tested implementation, best not to role your own crypto.

There are some optimizations of lamport signatures that seem relevant:

https://en.wikipedia.org/wiki/Lamport_signature

The main issue I see with trying to use lamport signatures, is the size, and even with optimizations, i think 2 commit reveal chains per did is more cost efficient, but is it safe?

**Comment by OR13** [comment]
Its sorta related, but IMO, the operation signature algorithm should remain the same for commit reveal, signing operations, and anchoring transactions to the ledger, and it should be secp256k1 for Sidetree Bitcoin and Sidetree Ethereum implementations, it can be ed25519 for libra ;)

**Comment by csuwildcat** [comment]
After some discussion, I believe this is the desired instantiation of commit/reveal we should implement:

In its simplest definition, the scheme relies on a pre-commitment to a secret reveal value _SV_ embedded as a commitment hash _C_ in a prior DID operation object, which is later revealed to observers to validate the next operation via publication of the SV. The secret selected by the user should be a sufficiently random value but technically, observing nodes do not care what it is (though there are constraints, and suggested methods for how to generate _SV_ in a way that eases the burden on users and wallet developers).

> NOTE: throughout the scheme we assume a deterministic secp256k1 signing implementation (adherent to [rfc6979](https://tools.ietf.org/html/rfc6979)) is being used.

**Creating a commitment (_C_) for a DID operation**

1. Generate a signature over the DID operation payload hash (in the case of a Create op, this will be the DID Unique Suffix)
2. Hash the resulting signature to generate the secret value _SV_, which will later be revealed when performing the next DID operation.
3. Hash SV to generate the commitment hash _C_.
4. Add the commitment hash to the protected header of the JWS protected header of the operation object.

**Revealing a Secret Value (_SV_)**

1. Use the key (or keys) previously used to create SV and C during the previous operation to again sign the previous operation payload hash
2. Hash the signature to recover _SV_
3. Create a new commitment _C_ value based on the new operation's payload has using the steps above.
4. When including the new operation in a batch, reveal _SV_ in the Anchor File DID map as evidence of legitimate inclusion for the next operation

> NOTE: if you are leveraging an external node for inclusion of your op, and the node was malicious, it could exclude your op from its next batch and spam your DID with false op indicators until you detected it in the next block and broadcast your op through another node or did so directly yourself. This does not mean they can steal your DID, just that they can spam false indicators that degrade resolution time of your ID (one entry per batch/block).

Using the method outlined above, we effectively eliminate the general class of DID Denial of Resolution attacks by preventing random parties to claim op inclusion by DIDs they cannot prove control over.

**Comment by csuwildcat** [comment]
Something to note: a separate commit/reveal chain must be maintained for Recovery operations, as those operations exist under the assumption that general protocol-active keys have been compromised, in which case any secret value based on them is no longer viable for revealing to prove legitimacy of op inclusion.

**Comment by OR13** [comment]
^ this is perfect, there is no need to use the previousTransactionTimeHash values if the header is used for transport of the next commitment. If you needed to put the commit and the reveal in the operation payload, then you would not be able to calculate the commit based on the payload hash, since inserting the commit would change the payload hash.

Much better to just use the header.
