### ISSUE TITLE
Consider methods of restricting the resolved DID Document size

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#264]
Some options are:

- Restrict number of entries in `service` and `publicKey` properties.
- Restrict max raw size of the DID Document (would require deterministic JSON serialization).

This can restrict the size of the returned DID Document by any DID resolution, especially useful against spam with large/forever growing DID Document.

**Comment by gjgd** [comment]
I think rather than restricting the size of the whole DID Document, it makes more sense to restrict the size of individual entries in the `service` and `publicKey` lists + the length of those lists.

For example, restricting the publicKey property to be a list of 10 items, and each item should not be more than 4096 bits (in order to support RSA4096 which is probably be the biggest key length we would want to support).

**Comment by csuwildcat** [comment]
I don't see how we'll be able to enforce this in any impactful way, given you'd have to actively have the doc compiled to the present state to know if incoming changes exceed any of the proposed limits. If you can't know until compile time, what could you realistically do in response?

**Comment by csuwildcat** [comment]
I'm in favor of closing this, because, as I previously stated, there's no effective enforcement at the protocol level.

**Comment by OR13** [comment]
I agree, let this be a method specific concept.

**Comment by isaacJChen** [comment]
Method specific, will close.
