### ISSUE TITLE
Add batch file compression.

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#28]

**Comment by csuwildcat** [comment]
I would propose that max batch size be based on a minified (and gzipped?) number of bytes that the entire batch payload must not exceed.

The next question, once a batch is evaluated to be under the max batch size, is whether or not we should enforce a max op size. This comes with a few considerations:

1. Basing this on either total size vs size of an individual op may require different PoW assessment, given a batch that is 10MB but only contains 2 ops, one that's 9.9MB and one that is 0.1MB should probably require a PoW that is op-size relative. If you just went with an op size limit, you could enforce a less complex PoW assessment, wherein it is the same for each op, regardless of exactly what its per-op size is. At first glance, I think this makes a case for enforcing a per-op size, vs wildly variable size ops that all must fit in a max batch size.
2. Allowing wildly variable op sizes could also present a challenge for rooting nodes who hope to provide a roughly constant number of ops they can root for inbound callers. If a rooting node is limited to 1 txn per block (because that's all they are willing to expend), a malicious caller could crowd out useful ops more easily by posting a bunch of large, useless, but technically valid ops, just to effectively limit the usefulness of the rooting node to others.

Given the considerations above, it seems like the clear answer is to have a max batch size that no batch can exceed, as well as per-op max size that each individual op must not exceed.
