### ISSUE TITLE
Design and implement operation rate limiting (max ops per block)

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#320]

**Comment by csuwildcat** [comment]
To record our proposed choice for operation selection, I'll note that there's preliminary consensus between some implementers to include txns on a highest-fee-first basis. Let's socialize this and finalize a selection strategy as soon as possible.

**Comment by isaacJChen** [comment]
### Algorithm: 

**OperationRateLimiter (new):** 

1. Takes in an array of TransactionModel ordered in transactionTime and are consecutive transactions 

2. Output an array of TransactionModel that should be stored 

3. OperationRateLimiter keeps its state so if the next array passed in contains transactions from the same block, it can continue processing. 

_Detailed implementation_ 

1. Takes in an array of transactions as input (assuming ordered in transactionTime and are consecutive transactions) 

2. For each transaction, if current transaction is from the same block as previous, put transaction into a priority queue ordered by transactionFee. 

3. If current transaction is not from the same block as previous, get top N highest fee transactions from the priority queue to fill M operations that the node should store. 

(EX: If we have 5 transactions in block A, with 10 ops, 13 ops, 4 ops, 23 ops, 45 ops respectively and fee paid from highest to lowest in that order, and we want to store M=25 operations in the current block, we would take N=2 transactions, because 10 + 13 = 23, and the next highest fee transaction with 4 ops will exceed 25 so we stop there. )

4. After the previous block is finish processed, empty the priority queue, put the current transaction in, and repeat step 2 to 4. 

5. When reach the end of array, OperationRateLimiter keeps its state including remembering which block it is currently processing and the state of the priority queue, so if the next array has transactions from the same block, it can continue processing. 

 

**Observer:** 

1. Observer has an OperationRateLimiter 
2. Reads in x number of latest transactions from blockchain, ordered by transactionTime (which block they are in) 
3. Passes the transactions to OperationRateLimiter, and get an array of transactions to process. 
4. Process and write to operationStore. 

 

**Open Questions:** 

How many operations should we store from each block?  

It will be parameterized and configurable. Currently, maxOpertaionPerBatch is 10,000, and each block can have on average more than 500 transactions. The max operation byte size is 2,000. Assuming sidetree transactions take up 10% of all bitcoin transactions, there can potentially be 500,000 operations per block, and 72,000,000 operations a day, which equates to 144 GB of operations a day, and 52.56 TB of operations a year. We can set a target data size to store in the operation store (such as 25 TB so we take roughly 240,000 ops per block), consider how often we will create checkpoints (to my understanding, the more check points, the more often we can wipe old operations, let me know if I misunderstood), and use the target data size to rate limit. 

 

How to remember state when the node dies?  

Observer keeps track of last transaction, it can be passed into OperationRateLimiter on instantiation. 

 

Why base fee on transaction rather than operation? 

It encourages batching while still allowing individuals to pay a relatively small price (a few dollar) to get their stuff in the network if they choose to do so.

**Comment by csuwildcat** [comment]
@isaacJChen max op size should be 1k, not sure where 2k came from. (@thehenrytsai, perhaps this was an old var that wasn't updated?)

**Comment by csuwildcat** [comment]
One question that's worth considering: even with a max number of ops, would moving to a per-byte fee assessment make more sense?

**Comment by csuwildcat** [comment]
I'll note that you don't want to be too aggressive with checkpoint intervals in your thinking about the clearing of ops, because there is a diminishing-to-negative return on checkpoints at the point where the average DID has less than somewhere between 1.5-2 updates within the active window. This is because a checkpoint forces DIDs that have not had updates to create a new checkpoint/recovery op they otherwise would not have created, resulting in a net addition of state data for their DID.

**Comment by isaacJChen** [comment]
continuation in here
https://github.com/decentralized-identity/sidetree/issues/378

Will close this one.
