### ISSUE TITLE
optimize bitcoin processor rpc calls

### ISSUE THREAD

**Issue by isaacJChen** [decentralized-identity/sidetree#430]
Right now, each getBlock method call to bitcoin core takes about 700ms on main net when the block size gets big (700ms for a ~1mb block). We call them sequantially for each block since the genesis block, which means bitcoinProcessor initialization can take days. 

We want to find a way to speed up the process.

**Comment by csuwildcat** [comment]
There's a previous Issue about this that the Core devs chimed in on: https://github.com/bitcoin/bitcoin/issues/8614

**Comment by sambarnes** [comment]
Since this is only an issue on the first initialization, one option might be to:
* postpone starting of the bitcoin node
* use something like a `sidetree import <PATH>` command to initialize directly from the bitcoin node's leveldb
** for example: [partity bitcoin client importing bitcoin-core blocks](https://github.com/paritytech/parity-bitcoin#importing-bitcoind-database)
* start the bitcoin node normally once sidetree releases leveldb

The primary downside of this approach is that you would have to find / maintain a TS wrapper for bitcoin-core's leveldb formats. Might not be the largest effort though, as you only need one operation: getting raw block data by hash.

**Comment by isaacJChen** [comment]
https://github.com/decentralized-identity/sidetree/pull/436

^ closed PR that may be used in the future for this issue

**Comment by isaacJChen** [comment]
https://github.com/decentralized-identity/sidetree/pull/765

**Comment by isaacJChen** [comment]
Done
