### ISSUE TITLE
Change create & recover operation request to supply the initial document state using patches

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#449]

**Comment by OR13** [comment]
Create is a patch from `{}` to: did document without id, and using fragids for all `id` properties that are normally required to be URIs...

Recover is a patch from `{ existing did core spec compliant doc1 }` to `{ existing did core spec compliant doc2 }`, where doc1 is completely replaces with doc2.

Both should use a full document update json patch IMO... unless we are confident that we know the JSON Schema for a did document... (we don't) see: https://github.com/w3c/did-core-registries/pull/11

**Comment by OR13** [comment]
We discussed 2 proposals:

1. Keep everything the same.

2. Wrap Create and Recovery operations in patches, so that all operations are patches... so the API is consistent.

We seem to have rough agreement on: 2... understanding that it adds a small amount of bloat, but makes the API (Operations Structures) more consistent.

We agreed that we can use "Patches" without agreeing that they be RFC JSON Patches or JSON Schema custom patches... We agreed that there are 2 locations where we want to address performance:

1. Observation Time
2. Resolution Time

We agreed that DID Methods can make different choices here.
