### ISSUE TITLE
Could we use hashing as a proof of fee

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/sidetree#595]
Rather than using monetary aspects, could we leverage a feature of v1 method to use PoW for spam protection instead of fees?

**Comment by csuwildcat** [comment]
The beauty of making proof of fee based on a blockchain's native token itself, is that in most chains (e.g. Bitcoin) the higher the fee paid in the txn, the more likely your txn is to make it into the block. For this reason, proof of fee via txn fees does two things at once: 1) enforces a spam barrier that has provable costs, and 2) elevates Sidetree-bearing txns above others that miners include in blocks.

**Comment by kdenhartog** [comment]
Couldn't you achieve the same properties by having hashes with greater number of zeros get processed first? I'm trying to be cognizant of the cases where people don't want to possess tokens or can't pay but are willing to wait.

**Comment by csuwildcat** [comment]
Lots to unpack with this, but do know that we discussed this (and many other ideas) before settling on Proof-of-Fee. Perhaps you and I can chat first, and distill the conversation to some replies here, so we don't rehash all that in long-stream of comments?

**Comment by thehenrytsai** [comment]
> people don't want to possess tokens or can't pay but are willing to wait.

We definitely considered proof-of-work before proof-of-fee, in fact, it was our first preference. But in the end, the goal is to deter spam, and unless people are willing to wait for a super long time (we are talking ~5 - 6 order of magnitude of time assuming spammers are using ASICs), proof-of-work will help the spammers, not deter them. Rough math says 1 second for an ASIC chip = weeks for an average user.

**Comment by kdenhartog** [comment]
I agree that simple PoW would not be asic resistant and that in order to effectively handle spamming the difficulty would skew heavily around ASICs to the point where it would take weeks to generate on a mobile device. 

To combat this difficulty skewing, I was thinking the difficulty would be set per IP address/per block. For example, IP 10.0.0.1, which is non-malicious submits txn 1 with a single leading 0 on the hash. This transaction is considered acceptable because the hash difficulty is met and the node has not seen transactions from this IP during this batch.

However, IP 10.0.0.2 is a malicious ASIC. Let's say this ASIC completes the initial difficulty of a single leading 0 with ease. In order for it to submit another transaction, it must submit a new transaction with two leading 0s for it to be accepted. For a third it must submit it with 4 leading 0s, and for a fourth successful transaction it must submit it with 8 leading 0s. 

I'll admit this probably doesn't solve all the cases of handling spam and could use some additional design work. Particularly around front loading of transactions by prepping transactions and then handing off to bots in a botnet with unique IPs. However, I think much of this can be solved with a "local difficulty" (difficult that ratchets exponentially per IP) and a "whole node difficulty" (whether the base PoW of the node should start at 1 leading 0s or n leading 0s).

Implementing this definitely does not need to be a specV1 feature. Rather, I'm hoping we keep this as a backup plan in case we find users are adverse to paying for transactions (for whatever reason although I've heard of some good approaches to handle payment without tokens) or we find that the price necessary to prevent spam is exclusionary to economically disadvantaged portions of the population.

**Comment by csuwildcat** [comment]
After talking out of band, it is clear there is a bit of a misunderstanding about which layer/aspect of spam this issue was created to address. There are two types of spam that Sidetree nodes must mitigate:

1. Spam of the network as a whole, at the actual chain/operation layer - for example: attackers creating loads of DIDs and txns on the target ledger to get nodes to process/store more data.
2. Spam of whatever endpoints a given node exposes for various reasons - for example: if a node leaves its resolution route open to all, it will get lots of resolve requests, or if (for some reason) a node exposes its write capacity to the open internet to take ops for people and gets plastered with requests to anchor ops.

Spam of type 1 is something that must be addressed at the chain/protocol layer, so that all nodes can apply the same deterministic rules/processes to mitigate spam. You can't really do anything that relies on subjective judgements or external oracles. Instead, you must use things like native txn fees and other forces present in the underlying substrate to architect mitigations.

Spam of type 2 can be mitigated however a node wants, and really isn't any different than how you'd mitigate spam to any other type of server - you need to vet the inbound calls to with some criteria or process you choose. There are countless ways to do this, but some are: forcing account login, email-granted pseudonymous auth tokens that are decremented based on use, etc.

This thread seems to be about spam type 2, not the actual Proof of Fee in some of the Sidetree implementations, like ION, that mitigate spam type 1.

**Comment by kdenhartog** [comment]
Agreed, I was only thinking about type 2 spamming, not type 1. I'll go ahead and close this issue now that we've got this documented as well. Thanks for providing the additional details to help me understand it a bit better.
