### ISSUE TITLE
publicKeyJwk in overlapping contexts

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#615]
I assume should either be made the same `sec:publicKeyJwk` as in `https://www.w3.org/ns/did/v1`  or removed from `context-v1.jsonld`.

In https://www.w3.org/ns/did/v1:

```
    "publicKeyJwk": {
      "@id": "sec:publicKeyJwk",
      "@type": "@json"
    },
```

In https://identity.foundation/sidetree/context-v1.jsonld:
```
    "publicKeyJwk": {
      "@id": "sidetree:publicKeyJwk",
      "@type": "@json"
    }
```

**Comment by troyronda** [comment]
@OR13 what do you think we should do with this one?

**Comment by OR13** [comment]
we should use did core... we are not allowed to overwrite did core actually.

The spec can define the term again, but it should point to the normative defintion at did core.

**Comment by csuwildcat** [comment]
No idea what this is about, but can we close it?

**Comment by OR13** [comment]
@csuwildcat when a term in a did document is not defined in a context, it creates an invalid did document... so sidetree did documents that contained "usage" were not valid, and would explode when used with JSON-LD, until we defined "usage" in a custom context.

Sidetree supports this custom context today: https://github.com/decentralized-identity/sidetree/blob/master/contexts/sidetree-v0.0.0.jsonld#L7

You can see that we are defining publicKeyHex, because it's not defined in did core... if it were, we would remove it from our context, as we have done for publicKeyJwk.


I am closing this issue now, because it is resolved.
