### ISSUE TITLE
Do we have an example for using this sidetree core ? 

### ISSUE THREAD

**Issue by bjwswang** [decentralized-identity/sidetree#648]
I am recently leanring to use `sidetree` to manage DIDs .  There are many protocols without any example code  which is really not good for beginners . 
 I start a sidertree core node,then I want to send a request to sidetree core node to create a new did. There is doc showing what data the api needs, but the data itself is complicated to construct. That would be better if an example is there .

**Comment by bjwswang** [comment]
Hi @OR13 , do you konw where to start ?  Thank you in advance!

**Comment by bjwswang** [comment]
I found lots of unit tests here https://github.com/decentralized-identity/sidetree/blob/master/tests/core which also contains the code but not very clear to beginners.

**Comment by bjwswang** [comment]
@OR13  btw... do we have any IRC or slack channel for communication ?

**Comment by OR13** [comment]
@bjwswang we don't currently have any community chat, but its clear that one would be helpful. cc @csuwildcat @thehenrytsai ... 

The current version of sidetree is fairly unstable, and we are still working towards spec v1.

hopefully the documentation for beginners will emerge as we get closer to spec v1 release.

**Comment by bjwswang** [comment]
@OR13  excellent!

**Comment by fabianekc** [comment]
@bjwswang I'm also very interested in documenting and using sidetree. I started a Github Repo with a tutorial here: https://github.com/ownyourdata/did-ion 

@csuwildcat @OR13 when do you think it makes sense to start working on a Tutorial vor v1.0? I don't have a problem if things change and I need to redo sections (as long as things already start converging :-)

**Comment by csuwildcat** [comment]
I'd say folks can feel confident working on this sort of stuff by ~May 27th, which will be absolute last call for any mods to major aspects of this version of the spec before it goes out for testing with beta implementations.

**Comment by bjwswang** [comment]
@fabianekc maybe we can contribute a best practice tutorial for this sidetree protocol.
btw.. what's the difference between ION and sidetree ?

**Comment by OR13** [comment]
Sidetree is a Ledger Agnostic Protocol for building scalable decentralized identifiers which is developed under DIF IPR Protection here:

https://github.com/decentralized-identity/sidetree

The sidetree spec, and reference implementation for typescript is hosted in this repo ^.

ION is a DID Method built on Bitcoin and IPFS using the Sidetree Protocol... its primary contributors are Microsoft employees, but there are others, its repo is here:

https://github.com/decentralized-identity/ion

Element is a DID Method built on Ethereum and IPFS using the Sidetree Protocol... its primary contributors are Transmute employees, but there are others, its repo is here:

https://github.com/decentralized-identity/element

TrustBloc is a DID MEthod built on Hyperledger Fabric and IPFS using the Sidetree Protocol... its primary contributors are SecureKey employees, but there are others, its repo is here:

https://github.com/trustbloc/trustbloc-did-method


Unfortunately, due to repository / module software architecture decisions beyond my control... sidetree reference implementation is almost 90% the same as ION... which is great for ION, but kinda sucks for Element and Trustbloc... We will be addressing this issue when we can. you can track progress on it here: https://github.com/decentralized-identity/sidetree/issues/346

**Comment by fabianekc** [comment]
@OR13 thanks a lot for this summary - I'll include it in the tutorial.

@bjwswang my plan is to start again on the weekend and use the dev branch of ION (https://github.com/decentralized-identity/ion/tree/dev) If you like I can invite you to the OwnYourData Slack and we can discuss any open questions there.

In the long run it would be great to extend the Tutorial also to Element (the notary service from OwnYourData uses the Ethereum mainnet and it'd be nice to focus on a single blockchain for me)

**Comment by csuwildcat** [comment]
FYI: Sidetree 1.0 is days away from a final draft and we're reading for community review. If this is still a ticket with action items to track, let us know.

**Comment by decentralgabe** [comment]
Closing, handled.
