### ISSUE TITLE
Query about kebab case recommendation in did state patches

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/sidetree#749]
It appears throughout the spec in most places we are using `snake_case` as the convention for any JSON keys, however the [did-state-patches](https://identity.foundation/sidetree/spec/#did-state-patches) section recommends using kebab case is there a rationale for this being different?

**Comment by OR13** [comment]
pretty sure @csuwildcat just decided to use them for that section.

the are values not properties, so Im not sure that its matters, and I would also guess that Microsoft cannot change this now, so I suggest we either add a note to the spec warning about the difference or close this issue with no changes to the spec.

Should we add a note?

**Comment by csuwildcat** [comment]
The spec-wide snake case thing was never about dictating that all _values_ of objects have a certain case (not even sure that's a fruitful endeavor), it was about standard properties, because the convention in JS/JSON land is to use underscored properties for many ergonomic reasons, such as:

- Don't have to screw around with bracket property value setting (I just puked in my mouth)
- Double clicking an underscored string selects the whole string, not just a segment.
- Camel case looks like shit, for example heresSome props with the same letterRight nextTo each other (puked in mouth again)

We could add a note, but I don't personally believe this warrants it.

**Comment by tplooker** [comment]
Im struggling to understand your rationale here, the above comments appear to advocate for snake_case? however you chose to use kebab-case with the did state patch type values? e.g `add-public-keys` which is it you prefer as your comments above only really call out camelCase? My issue was there being kebab-case vs snake_case in different parts of the spec

**Comment by csuwildcat** [comment]
We were only concerned with properties, because there's a clear common convention for them. This wasn't a consideration, but then custom Action types would have a strange look, in my opinion. Is this something we need to break implementation compat to change?

**Comment by OR13** [comment]
Agree, closing this issue. @tplooker feel free to reopen, but 10 days and no comments, and a desire not to break compatibility seem like good reasons to close.
