### ISSUE TITLE
spec: handling patch errors inconsistent across operations 

### ISSUE THREAD

**Issue by sandrask** [decentralized-identity/sidetree#836]
According to Step 6 in https://identity.foundation/sidetree/spec/#create-operation-processing if patch fails we should continue to next patch ("next entry").

In case of "recover" we are supposed to go to next operation
In case of "update" we are supposed to halt processing 

Behaviour should be consistent for all operations.

**Comment by csuwildcat** [comment]
The reason you can't ever halt processing of a next candidate Recovery/Deactivate operation is because if you did, your ID would be stuck. This is in contrast to Updates, which don't act as a block to further modification, given you can always recover with a Recovery op. We can discuss modifying the Update behavior on the call today, if that is of interest to folks.

**Comment by sandrask** [comment]
@csuwildcat I agree that we should not halt processing.

**Comment by sandrask** [comment]
Reference application is now matching the spec for recover and create operations (#744).  Update will be discussed in #834
