### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by llorllale** [decentralized-identity/sidetree#842]
The use of `@base` as a mechanism specific to JSON-LD to fix the document's IRI is non-compliant with the did-core spec which specifically constrains the data type of `@context` to be URIs for _all_ core representations:

> The value of the @context property MUST be one or more URIs, where the value of the first URI is https://www.w3.org/ns/did/v1. All members of the @context property SHOULD exist in the DID specification registries in order to achieve interoperability across different representations. If a member does not exist in the DID specification registries, then the DID Document will not be interoperable across representations. 

[Source](https://w3c.github.io/did-core/#json-ld).

did-core recently added support for [relative URLs](https://w3c.github.io/did-core/#relative-did-urls). @csuwildcat suggested using this may suffice for sidetree's requirements.

**Comment by csuwildcat** [comment]
If the base URI of a DID Document is established via the `id` property now, that should suffice to resolve the URL references in the document. I am fine with pulling `@base` if that seems like the best way forward.

**Comment by troyronda** [comment]
@csuwildcat @OR13 @llorllale Should this issue be closed?

**Comment by OR13** [comment]
Before we close this, let me say that relative URIs are a huge pain in the ass for verifiable credentials.... all over your code you will be doing stuff like this:

```ts
key.id = key.controller + key.id
issue(vc, key)
```

why? 

because the whole point of VCs is to know where keys are... and relative URIs don't do that... 

that being said... they look pretty.

and technically `@base` may not be required (depending on your JSON-LD processor).... I would suggest keeping it until you have written enough tests to prove to yourself that its not necessary...

in our did key implementation, we do whatever sidetree does (as long as its valid JSON and JSON-LD).

**Comment by OR13** [comment]
I propose we close this PR and that sidetree include `@base` just to be safe / compatible with JSON-LD playground.... if you are worried about string duplication... google compression... and they facepalm when you realize that it destroys the only value of relative URIs, other than readability.

**Comment by troyronda** [comment]
`@base` is a `SHOULD` in Sidetree and the test vectors include `@base`.
