### ISSUE TITLE
Update document is not processing purposes properly

### ISSUE THREAD

**Issue by sandrask** [decentralized-identity/sidetree#905]
Update "operationRequest" is adding new key with id "additional-key" and following purposes:
-   "verificationMethod"
-    "authentication"
-    "assertionMethod"
-    "capabilityInvocation"
-    "capabilityDelegation"
-    "keyAgreement"

However,  after update operation resolution result only has authentication section populated.
https://github.com/decentralized-identity/sidetree/blob/master/tests/vectors/resolution/afterUpdate.json

In addition to "authentication" section I  expected to see the following: 
    "assertionMethod": [
      "#additional-key"
    ],
    "capabilityDelegation": [
      "#additional-key"
    ],
    "capabilityInvocation": [
      "#additional-key"
    ],
    "keyAgreement": [
      "#additional-key"
    ],

**Comment by sandrask** [comment]
Note: "newKey" in recover request has same issues

**Comment by thehenrytsai** [comment]
This is a dup to issue #894. We are aware that we need to update the implementation based on this weeks' WG meeting discussion, just haven't gotten around to it this week, will definitely be done by end of next week.

Since this has more detail (thank you!), I am going to close the other issue as dup.

**Comment by isaacJChen** [comment]
Addressed in the commit above.
