### ISSUE TITLE
Sidetree API spec needs to update JSON examples and property names to align with prior agreements

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/sidetree#923]
This is a place holder issue to address updating the JSON examples and property names to align with the agreements we put in place around the style guide. Seems like it should just be a spec update, but @thehenrytsai or @csuwildcat please let me know if this is needed in the reference implementation as well. I'll follow up with a PR later this week to get things fixed up.

**Comment by rado0x54** [comment]
Maybe I can specifically add here that section
https://identity.foundation/sidetree/api/#create
is confusing, because the example references `suffixData` while the description mentions `suffix_data` and it seems like Trustbloc and Elements currents differ in their implementation in this regard.

Hope that is the correct ticket to address this.

**Comment by kdenhartog** [comment]
Yeah this would be the good place to add that in rather than creating a new issue.

**Comment by csuwildcat** [comment]
Done.
