### ISSUE TITLE
Implement recover operations

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#93]
Recovery mechanism will dictate how signature verification will be performed for delete and recovery operations.

**Comment by csuwildcat** [comment]
We can quickly spec out one simple option to just include a recovery public key, and assume a payload will be signed with it.

**Comment by OR13** [comment]
example recovery from element:

```
const payload = {
      did: `did:sidetree:${uid}`,
      operationNumber: 2,
      previousOperationHash,
      patch: [
        // first op should update recovery key.
        {
          op: 'replace',
          path: '/publicKey/1',
          value: {
            id: '#recovery',
            type: 'Secp256k1VerificationKey2018',
            publicKeyHex: recoveryKeypair2.publicKey,
          },
        },
        {
          op: 'replace',
          path: '/publicKey/0',
          value: {
            id: '#primary',
            type: 'Secp256k1VerificationKey2018',
            publicKeyHex: primaryKeypair2.publicKey,
          },
        },
      ],
    };
```
Per the spec, a new recovery key is required to be present, but other replacements, deletions are optional.

Recovery is identical to update, except that a specific patch operation is required and the recovery payload is to be signed by a "recovery" key... I took this to mean a key with the id `#recovery`, which means that recovery is not possible until such a key exists in a did document.

**Comment by OR13** [comment]
on a related note, it seems very odd that delete is not also a patch operation, that removes all keys for the doc.

Per the DID spec, a public key that does not exist is considered revoked.

https://w3c-ccg.github.io/did-spec/#public-keys

so any credentials would be auto revoked if they were signed by `did:sidetree:uid#key`, and this key was not present in the resolved document.

Also consider renaming "delete" to "deactivate" 
https://w3c-ccg.github.io/did-spec/#deactivate

**Comment by OR13** [comment]
I'm taking a second pass at this in element as I apply the updates to the protocol.

It seems like the operation processor needs to be aware of a couple things here:

1. A public key with id `#recovery` can only be updated by an op signed by that key, which includes a new public key with id `#recovery`. (implies update logic to prevent any patch that would violate this).
2. delete has no such requirement.

It seems like the generalization here is that sidetree has a way of recognizing a new / not very well spec'ed concept in JSON-LD Signatures called [Proof Purposes](https://github.com/digitalbazaar/jsonld-signatures#introduction), from some attribute of the publicKey, and that operations with a purpose that are signed by a key that supports that proof purpose are valid.

For now in element, we assume proof purpose from the id for example: `#recovery`, or `#primary`.

Right now in element we assume the following purposes from these ids:

`#primary`
- create, update, delete

`#recovery`
- recover (must include a new recover key)

If delete/deactivate is truly permanent action, I believe a deleted DID should have a document which is minimized (all data that can be removed should be), since there will be no chance to do this after delete, and any future resolution is likely to be returning stale data, and there won't be an obvious way to tell that the DID was deleted per the spec, so signatures might validate that should not (causes interoperability confusion), and removing keys is the only DID Method agnostic mechanism for revoking keys...

**Comment by thehenrytsai** [comment]
Feature consider implemented, file new issues if feature changes/updates are required.
